name: spend_tracker
description: "Track Spendings"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-174.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#15616d"
  android_12:
    color: "#15616d"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/