name: spend_tracker
description: "Track Spendings"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-174.3.beta <4.0.0'

dependencies:
  auto_route: ^7.8.4

  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/